export const categoryIcons: Record<string, string> = {
  'accounting-finance': '💰',
  'administrative': '📋',
  'banking-finance': '🏦',
  'customer-service': '🎧',
  'design': '🎨',
  'education-instruction': '📚',
  'engineering': '⚙️',
  'food-beverage': '🍽️',
  'health-care': '🏥',
  'hospitality-tourism': '🏨',
  'human-resources': '👥',
  'imam-islamic-studies': '🕌',
  'it-software-development': '💻',
  'legal': '⚖️',
  'management': '📊',
  'marketing': '📣',
  'media-communications': '📡',
  'medical-nursing': '🩺',
  'nonprofit-ngo': '🤝',
  'personal-care-home-health': '❤️',
  'project-management': '📅',
  'remote-only': '🌐',
  'retail': '🛍️',
  'sales': '📈',
  'scientific-research': '🔬',
  'security-public-safety': '🛡️',
}

export const defaultIcon = '💼'
